export const timeZoneData = {
    "Europe/London": "London, GBR",
    "Europe/Amsterdam": "Amsterdam, NLD",
    "Africa/Cairo": "Cairo, EGY",
    "Europe/Istanbul": "Istanbul, TUR",
    "Asia/Muscat": "Muscat, OMN",
    "Asia/Karachi": "Karachi, PAK",
    "Asia/Colombo": "Colombo, LKA",
    "Asia/Dhaka": "Dhaka, BGD",
    "Asia/Bangkok": "Bangkok, THA",
    "Asia/Shanghai": "Shanghai, CHN",
    "Asia/Tokyo": "Tokyo, JPN",
    "Pacific/Guam": "Guam, GUM",
    "Australia/Sydney": "Sydney, AUS",
    "Pacific/Norfolk": "Norfolk Island, NFK",
    "Pacific/Auckland": "Auckland, NZL",
    "Pacific/Honolulu": "Honolulu, USA",
    "America/Anchorage": "Anchorage, USA",
    "America/Los_Angeles": "Los Angeles, USA",
    "America/Denver": "Denver, USA",
    "America/Chicago": "Chicago, USA",
    "America/New_York": "New York, USA",
    "America/Santo_Domingo": "Santo Domingo, DOM",
    "America/Santiago": "Santigo, CHL",
    "America/Noronha": "Noronha, BRA",
    "Atlantic/Cape_Verde": "Cape Verde, CPV",
};
